# Generated by Django 5.2.7 on 2025-12-07 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='invitation',
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='respondent_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allowed_emails',
                'ordering': ['email'],
                'unique_together': {('owner', 'email')},
            },
        ),
        migrations.CreateModel(
            name='SurveyAllowedEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.allowedemail')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_emails', to='surveys.survey')),
            ],
            options={
                'db_table': 'survey_allowed_emails',
                'unique_together': {('survey', 'allowed_email')},
            },
        ),
        migrations.DeleteModel(
            name='SurveyInvitation',
        ),
    ]
